server:
  port: 18088


rta:
  app: nms                      #应用名称（全局唯一）
  type: manager                 # runtime or manager
  pid: rta-manager-01           #进程id（jvm进程id，在应用内唯一）
  address: 127.0.0.1            #部署IP地址（物理机、虚机、k8s节点IP地址）
  port: 18088                   #部署端口（物理机和虚机进程启动端口，k8s代理容器端口）
  heartDelay: 10                #心跳间隔时间（单位秒）
  retry: 10                     #ZkClient重试次数
  retryDuration: 5000           #ZkClient重试间隔事件，单位毫秒
  zkAddress: 127.0.0.1:2181
  zkSessionTimeout: 30000
  zkConnectionTimeout: 30000
  meta:
    k1: v1